language: php

php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

env:
  global:
    - setup=basic

matrix:
  include:
    - php: 5.6
      env: setup=lowest
    - php: 5.6
      env: setup=stable
  allow_failures:
    - env: setup=lowest
    - env: setup=stable
    - php: 7.0
    - php: nightly
    - php: hhvm
  fast_finish: true

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  - OCULAR_ENV='5.6'

install:
  - if ["$TRAVIS_PHP_VERSION" != "hhvm" || "$TRAVIS_PHP_VERSION" != "7.0" ]; then
    curl -LS https://pecl.php.net/get/event | tar -xz;
    pushd event-*;
    phpize;
    ./configure;
    make;
    make install;
    popd;
    echo "extension=event.so" >> "$(php -r 'echo php_ini_loaded_file();')";
    curl -LS https://pecl.php.net/get/libevent | tar -xz;
    pushd libevent-*;
    phpize;
    ./configure;
    make;
    make install;
    popd;
    echo "extension=libevent.so" >> "$(php -r 'echo php_ini_loaded_file();')";
    fi
  - curl -LS https://pecl.php.net/get/ev | tar -xz;
    pushd ev-*;
    phpize;
    ./configure;
    make;
    make install;
    popd;
    echo "extension=ev.so" >> "$(php -r 'echo php_ini_loaded_file();')";
  - curl http://get.sensiolabs.org/php-cs-fixer.phar -o php-cs-fixer.phar
  - composer self-update
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-source; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-lowest --prefer-stable; fi


script:
  - php -n php-cs-fixer.phar fix -v --dry-run
  - vendor/bin/phpunit --verbose --coverage-clover clover-data
  - if [ $(phpenv version-name) = $OCULAR_ENV ]; then wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover clover-data; fi

after_script:
  - php vendor/bin/coveralls -v
